---
title: "learning"
author: "WANGARI MUTUKU"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(tidyverse)
library(janitor)
library(sf)
library(readxl)
```

```{r call data, include=FALSE}
#reading the datasets

county_data<-st_read("County.shp") %>%
  rename(county=Name)
density_data<- read_excel("Density.xlsx")%>%
  clean_names()

##get county names in density data
densitycounties<-unique(density_data$county)
#get county names in shape files
shapecounties <-unique(county_data$county)
#get county names that are in density data but not in shape file data
densitycounties[which(!densitycounties%in%shapecounties)]
#recode missplet county names in density data
density_data<-density_data %>%
  mutate(county=recode(county,"Keiyo-Marakwet"="Elgeyo Marakwet","Murang'A"="Muranga"))

```


```{r cplot shape file data}
ggplot(county_data)+
  geom_sf(aes(geometry=geometry))
```







```{r merge data}
merged_density_data <-county_data %>%
  left_join(density_data,by=c("county"))
```

  
```{r plot density data}
ggplot(merged_density_data)+
  geom_sf(aes(geometry=geometry,fill=density_of_physician_hwf_per_10_000_population)) +
theme_void()+
  labs(x="",y="", fill="physcian Density", title="map showing the physcian density per county")+
  scale_fill_gradient(low="white",high="#2ca25f")
```

